// import { users } from "../consts/consts";

import WebSocket from "ws";
// import { users } from "../consts/consts";

export function createGame(data: any, ws: WebSocket) {
  console.log(data);
  const response = {
    type: "create_game", //send for both players in the room, after they are connected to the room
    data: {
      idGame: 0,
      idPlayer: 0 /* generated by server id for player in the game session, not enemy (unique id for every player) */,
    },
    id: 0,
  };

  ws.send(JSON.stringify({ ...response, data: JSON.stringify(response.data) }));
}
